# Use `sudo` as `@sudo`. This will check for `sudo` command and user type for you.
# You can add logs like below
#  @log "This is an info log"
#  @info "This is an info log"
#  @warn "This is an warn log"
#  @error "This is an error log"
name = "Hello"
shortname = "hello"
description = "This is just a sample tool to use as an example"
issue = ""

[apt]
sh = """
@info "Installing hello"
@warn "This is only a demo installation"
@info "Installed hello"
"""

[yum]
sh = """
@info "Installing hello"
@warn "This is only a demo installation"
@info "Installed hello"
"""

[pacman]
sh = """
@info "Installing hello"
@warn "This is only a demo installation"
@info "Installed hello"
"""

[apk]
sh = """
@info "Installing hello"
@warn "This is only a demo installation"
@info "Installed hello"
"""

[dnf]
sh = """
@info "Installing hello"
@warn "This is only a demo installation"
@info "Installed hello"
"""

[curl]
sh = """
@info "Installing hello"
@warn "This is only a demo installation"
@info "Installed hello"
"""
