name = "Gchrome"
shortname = "gchrome"
description = "Chrome browser installer"
issue = ""


[curl]
sh = """
curl -O https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
@sudo dpkg -i google-chrome-stable_current_amd64.deb
"""

