name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Get the list of modified installers only
        uses: technote-space/get-diff-action@v1
        with:
          PREFIX_FILTER: |
            installers/
      - name: Generate installers, update README.md & installers.toml
        if: env.GIT_DIFF
        run: ./generate.sh ${{ env.GIT_DIFF }}
      - name: Minify generated installers
        if: env.GIT_DIFF
        run: ./minify.sh ${{ env.GIT_DIFF }}
      - name: Finding the Related PR
        if: env.GIT_DIFF
        uses: jwalton/gh-find-current-pr@v1
        id: finding-related-pr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Found the related PR
        if:  env.GIT_DIFF && success() && steps.finding-related-pr.outputs.number
        id: related-pr
        run: |
          echo "The related PR is ${PR}"
          echo ::set-output name=pr_id::"${PR}"
        env:
          PR: ${{ steps.finding-related-pr.outputs.pr }}
      - name: Notify Gitter channel of creation of a new PR for new installers.
        id: initial-gitter-notification
        if: env.GIT_DIFF
        uses: juztcode/gitter-github-action@v1
        with:
          room-id: ${{ secrets.GITTER_ROOM_ID }}
          token: ${{ secrets.GITTER_TOKEN }}
          text: Creating a new PR for [the merged PR](https://github.com/${{ github.repository }}/pull/${{ steps.related-pr.outputs.pr_id }})
      - name: Create a pull request for README.md & installers.toml updates
        id: create-pr
        if: env.GIT_DIFF
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update installer scripts, README.md & installers.toml
          title: |
            Update installer scripts, README.md & installers.toml for #${{ steps.related-pr.outputs.pr_id }}
          body: |
            Updated installer scripts, `README.md` & `installers.toml` according to the changes done in the `installer.toml`s.
            This is a automatically generated PR in related to PR #${{ steps.related-pr.outputs.pr_id }}
          branch: update-readme-md-and-installers-toml-${{ steps.related-pr.outputs.pr_id }}
          labels: automated-pr, continious-delivery
      - name: Archive Production Artifact
        if: env.GIT_DIFF
        uses: actions/upload-artifact@master
        with:
          name: installers
          path: installers
      - name: Notify Gitter channel of the new PR created for new installers.
        if: env.GIT_DIFF
        uses: juztcode/gitter-github-action@v1
        with:
          room-id: ${{ secrets.GITTER_ROOM_ID }}
          token: ${{ secrets.GITTER_TOKEN }}
          text: Created [a new PR](https://github.com/${{ github.repository }}/pull/${{ steps.create-pr.outputs.pull-request-number }}) with installer scripts for [the merged PR](https://github.com/${{ github.repository }}/pull/${{ steps.related-pr.outputs.pr_id }})
          message-id: ${{ steps.initial-gitter-notification.outputs.message-id }}

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Get the list of modified installers only
        uses: technote-space/get-diff-action@v1
        with:
          PREFIX_FILTER: |
            installers/
      - name: Download Artifact
        if: env.GIT_DIFF
        uses: actions/download-artifact@master
        with:
          name: installers
          path: installers
      - name: Install Dependencies
        run: cd functions && npm install
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --project installer-to
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy to Google Cloud Bucket
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: installer-to
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: rsync -r installers gs://installer-to.appspot.com/
          cli: gsutil
